version: '3'
services:
  web:
    image: tjlaekem/ciaoestrela-web:latest
    build: .
    container_name: ciaoestrela_web
    networks: 
      - ciaoestrela
    ports:
      - 80:5000
    volumes:
      - ./src:/app/src

networks:
  ciaoestrela:
