version: 2
jobs:
  install:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: make install
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: make lint

  build:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: make build
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/
      - run: sudo pip install awscli
      - run: aws s3 sync build/ s3://ciaoestrela.co

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - lint
            - build
          filters:
            branches:
              only: master
