version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: npm install
      - run: npx eslint src/

  build:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: pwd
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project/
      - run: sudo pip install awscli
      - run: aws s3 sync build/ s3://dev.ciaoestrela.co

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
