version: 2
jobs:
  lint:
    docker:
      - image: node:12.2.0-alpine
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            apk add make
      - run:
          name: Install Requirements
          command: |
            make install
      - run:
          name: Lint
          command: |
            make lint

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - run:
          name: Install aws cli
          command: sudo pip install awscli

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - deploy:
          type: approval
          requires:
            - lint
