version: 2
jobs:
  install:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - attach_workspace:
         at: /
      - run:
          name: Lint
          command: npx eslint src/

  build:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run:
          name: Install requirements
          command: npm install
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - attach_workspace:
          at: /
      - run:
          name: Install aws cli
          command: sudo pip install awscli
      - run:
          name: List
          command: ls
      - run:
          name: List build
          command: ls build
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
