version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: npm install
      - run: npx eslint src/

  build:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - attach_workspace:
          at: /
      - run: sudo pip install awscli
      - run:
          name: List
          command: ls
      - run:
          name: List build
          command: ls build

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
